### ISSUE TITLE
OPC XML DA support

### ISSUE THREAD

**Issue by georgeslegros** [technosoftware-gmbh/opc-daaehda-client-net-standard#2]
Does this library support IPC XML DA?
If no, can someone point me to a suitable library? Ideally, this should be dotnet core and Linux compatible.

Thanks.

**Comment by technosoftware** [comment]
OPC XML-DA is not supported by this SDK. And also unknown if such an SDK exists.

If this is an option for you, you might consider using OPC UA, which is available for .NET Core and Linux. See [OPC UA SDK .NET Standard](https://github.com/technosoftware-gmbh/opc-ua-bundle-net-standard).

Best regards
